import { florianopolis } from ".";

export default {
  city_name: "Dourados",
  state: "Mato Grosso do Sul",
  country: "Brazil",
  lat: -22.222471,
  lng: -54.8242976,
  zoom: 15,
  properties: [
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
  ],
};
