export default {
  city_name: "London",
  state: "United Kingdom",
  country: "England",
  lat: 51.5287718,
  lng: -0.2416802,
  zoom: 11,
  properties: [
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
    {
      class: "",
      features: { bd: 0, ba: 0, sqft: 0 },
      coord: { lat: 0, lng: 0 },
      address: "",
      price: "",
      image: "",
    },
  ],
};
